/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as JuegoSlugRouteImport } from './routes/juego.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const JuegoSlugRoute = JuegoSlugRouteImport.update({
  id: '/juego/$slug',
  path: '/juego/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/juego/$slug': typeof JuegoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/juego/$slug': typeof JuegoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/juego/$slug': typeof JuegoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/perfil' | '/ranking' | '/juego/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/perfil' | '/ranking' | '/juego/$slug'
  id: '__root__' | '/' | '/perfil' | '/ranking' | '/juego/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  JuegoSlugRoute: typeof JuegoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juego/$slug': {
      id: '/juego/$slug'
      path: '/juego/$slug'
      fullPath: '/juego/$slug'
      preLoaderRoute: typeof JuegoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  JuegoSlugRoute: JuegoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
